apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-portal
      context: node-workspace
      docker:
        dockerfile: portal/Dockerfile
deploy:
  helm:
    releases:
      - name: portal
        chartPath: node-workspace/portal/helm-chart
        namespace: otus
        skipBuildDependencies: true
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-portal
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-identity
      context: node-workspace
      docker:
        dockerfile: identity/Dockerfile
deploy:
  helm:
    releases:
      - name: identity
        chartPath: node-workspace/identity/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-identity
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-orders-api
      context: node-workspace
      docker:
        dockerfile: orders-api/Dockerfile
deploy:
  helm:
    releases:
      - name: orders-api
        chartPath: node-workspace/orders-api/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-orders-api
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-billing-api
      context: node-workspace
      docker:
        dockerfile: billing-api/Dockerfile
deploy:
  helm:
    releases:
      - name: billing-api
        chartPath: node-workspace/billing-api/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-billing-api
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-notifications-api
      context: node-workspace
      docker:
        dockerfile: notifications-api/Dockerfile
deploy:
  helm:
    releases:
      - name: notifications-api
        chartPath: node-workspace/notifications-api/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-notifications-api
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-image-processor
      context: image-processor
      docker:
        dockerfile: ImageProcessor/Dockerfile
deploy:
  helm:
    releases:
      - name: image-processor
        chartPath: image-processor/helm-chart
        skipBuildDependencies: true
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-image-processor