apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-portal
      context: portal
deploy:
  helm:
    releases:
      - name: portal
        chartPath: portal/helm-chart
        namespace: otus
        skipBuildDependencies: true
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-portal
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-identity
      context: identity
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: identity
        chartPath: identity/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-identity
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-orders
      context: orders
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: orders
        chartPath: orders/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-orders
