apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-portal
      context: portal
deploy:
  helm:
    releases:
      - name: portal
        chartPath: portal/helm-chart
        namespace: otus
        skipBuildDependencies: true
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-portal
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-identity
      context: identity
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: identity
        chartPath: identity/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-identity
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-orders-api
      context: orders-api
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: orders-api
        chartPath: orders-api/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-orders-api
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-billing-worker
      context: billing-worker
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: billing-worker
        chartPath: billing-worker/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-billing-worker
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-billing-api
      context: billing-api
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: billing-api
        chartPath: billing-api/helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-billing-api
