apiVersion: skaffold/v2beta9
kind: Config
deploy:
  helm:
    releases:
      - name: aes
        chartPath: api-gateway/helm-chart
        namespace: otus
        skipBuildDependencies: false
        createNamespace: true
---
apiVersion: skaffold/v2beta9
kind: Config
deploy:
  kubectl:
    defaultNamespace: otus
    manifests:
      - api-gateway/ambassador/*
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-identity
      context: identity
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: identity
        chartPath: identity/helm-chart
        namespace: otus
        skipBuildDependencies: true
        createNamespace: true
        overrides:
          postgresql:
            metrics:
              enabled: false
              serviceMonitor:
                enabled: false
          metrics:
            enabled: false
            serviceMonitor:
              enabled: false
        artifactOverrides:
          image: vaagn/face-systems-identity
---
apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-orders
      context: orders
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: orders
        chartPath: orders/helm-chart
        namespace: otus
        skipBuildDependencies: true
        createNamespace: true
        overrides:
          postgresql:
            metrics:
              enabled: false
              serviceMonitor:
                enabled: false
          metrics:
            enabled: false
            serviceMonitor:
              enabled: false
        artifactOverrides:
          image: vaagn/face-systems-orders
