replicaCount: 1

configName: image-processor-config
secretName: image-processor-secret
image: vaagn/face-systems-image-processor

metrics:
  enabled: false
  serviceMonitor:
    enabled: false

rabbitmqOrdersQueue: orders_queue
rabbitmqUri: amqp://user:bX1DTrlOfH@infrastructure-rabbitmq:5672
minioClientConfig: '{"endPoint":"infrastructure-minio","port":9000,"useSSL":false,"accessKey":"minio","secretKey":"b75794cba71f409f8ed8ea2528857736"}'
