apiVersion: v2
name: billing-worker
description: A Helm chart for Kubernetes
type: application
version: 0.8.0
appVersion: 0.8.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
