apiVersion: v2
name: notifications-api
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.0.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
