apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configName }}
data:
  PRIVATE_KEY: {{ .Values.privateKey | b64enc | quote }}
  PUBLIC_KEY: {{ .Values.publicKey | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}