apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-notifications-api
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: notifications-api
        chartPath: helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-notifications-api
