apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-orders-api
      context: ..
      docker:
        dockerfile: orders-api/Dockerfile

deploy:
  helm:
    releases:
      - name: orders-api
        chartPath: helm-chart
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-orders-api
