{
 "title": "Identity API",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{pod=~\"identity.+\"})",
     "legendFormat": "Working Set"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"identity.+\"})"
    }
   ]
  },
  {
   "title": "Database (writes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"identity-db\"}[1m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Application Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "RPS by methods",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(identity_requests[1m]))",
     "legendFormat": "{{method}} rps"
    }
   ]
  },
  {
   "title": "Latency by methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum by (le, method)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "{{method}} 50%"
    },
    {
     "expr": "histogram_quantile(0.95,sum by (le, method)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "{{method}} 95%"
    },
    {
     "expr": "histogram_quantile(0.99,sum by (le, method)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "{{method}} 99%"
    },
    {
     "expr": "histogram_quantile(1, sum by (le, method)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "{{method}} max"
    }
   ]
  },
  { "title": "nginx Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "RPS by methods",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(nginx_ingress_controller_request_duration_seconds_count[1m]))",
     "legendFormat": "{{methpd}}"
    }
   ]
  },
  {
   "title": "Errors count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{status=~\"5.+\"}[1m]))"
    }
   ]
  },
  {
   "title": "Latency (summary)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum by (le)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "50%"
    },
    {
     "expr": "histogram_quantile(0.95,sum by (le)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "95%"
    },
    {
     "expr": "histogram_quantile(0.99,sum by (le)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "99%"
    },
    {
     "expr": "histogram_quantile(1, sum by (le)(rate(identity_latency_bucket[2m])))*1000",
     "legendFormat": "max"
    }
   ]
  }
 ]
}