apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-image-processor
      docker:
        dockerfile: ImageProcessor/Dockerfile
deploy:
  helm:
    releases:
      - name: image-processor
        chartPath: helm-chart
        skipBuildDependencies: true
        namespace: otus
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-image-processor