apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-portal
      context: ..
      docker:
        dockerfile: portal/Dockerfile
deploy:
  helm:
    releases:
      - name: portal
        chartPath: helm-chart
        namespace: otus
        skipBuildDependencies: true
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-portal
