apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user-api-chart.fullname" . }}
  labels:
    {{- include "user-api-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "user-api-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "user-api-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image }}:{{ .Chart.AppVersion }}"
            - name: GREETING
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configName }}
                  key: GREETING
          ports:
            - name: http
              containerPort: {{.Values.targetPort}}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe}}
              port: {{.Values.targetPort}}
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
