apiVersion: v1
kind: Service
metadata:
  name: {{ include "user-api-chart.fullname" . }}
  labels:
    {{- include "user-api-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "user-api-chart.selectorLabels" . | nindent 4 }}
