apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: identity-mapping
spec:
  prefix: "/api/(auth|users).*"
  prefix_regex: true
  host: arch.homework
  service: identity:8000
  regex_rewrite:
    pattern: "/api/(auth|users)"
    substitution: '/\1'
