apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-api-chart.fullname" . }}
  labels:
    {{- include "orders-api-chart.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: http
      protocol: TCP
      name: web
  selector:
    {{- include "orders-api-chart.selectorLabels" . | nindent 4 }}
