apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configName }}
data:
  RABBITMQ_BILLING_QUEUE: {{ .Values.rabbitmqBillingQueue }}
  RABBITMQ_URI: {{ .Values.rabbitmqUri }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@billing-worker-postgresql:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}