replicaCount: 1

configName: billing-api-config
secretName: billing-api-secret
image: vaagn/face-systems-billing-api
livenessProbe: /api/health

servicePort: 8000

postgresql:
  enabled: true
  postgresqlUsername: nestjs-user
  postgresqlDatabase: billing-db
  postgresqlPassword: dev-password
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
  service:
    type: NodePort
    nodePort: 30020
    port: '5432'

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

rabbitmqBillingQueue: billing_queue
rabbitmqOrdersQueue: orders_queue
rabbitmqUsersQueue: users_queue
rabbitmqUri: amqp://user:bX1DTrlOfH@infrastructure-rabbitmq:5672
