# Default values for user-api-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 5
image:
  repository: vaagn/user-api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: '1.0.0'

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''

serviceAccount:
  create: false
  annotations: {}
  name: ''

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

deployment:
  livenessProbePath: /health
  livenessProbePort: 3000

service:
  type: NodePort
  selector:
    app: user-api
  port: 8000
  targetPort: 3000

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: arch.homework
      paths:
        - path: /otusapp/vaagn($|/)(.*)
          pathType: Prefix
          backend:
            service:
              name: user-service
              port:
                number: 8000
  tls: []
  resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}

tolerations: []

affinity: {}
