apiVersion: skaffold/v2beta9
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: vaagn/face-systems-identity
      docker:
        buildArgs:
          NPM_TOKEN: '{{.NPM_TOKEN}}'
deploy:
  helm:
    releases:
      - name: identity
        chartPath: helm-chart
        namespace: otus
        skipBuildDependencies: true
        createNamespace: true
        artifactOverrides:
          image: vaagn/face-systems-identity
