apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: face-systems-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: aes-ambassador
                port:
                  number: 80
          - path: /portal(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: portal
                port:
                  number: 80
