apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: "myapp-jwt-filter"
spec:
  JWT:
    jwksURI: "http://identity:8000/api/auth/.well-known/jwks.json"
    insecureTLS: true
    renegotiateTLS: freelyAsClient
    validAlgorithms:
    - "RS256"
    requireAudience: false
    requireIssuer: false
    requireIssuedAt: false
    requireExpiresAt: false
    requireNotBefore: false
    injectRequestHeaders:
    - name: "X-Token-String"
      value: "{{ .token.Raw }}"
    - name: "X-Login"
      value: "{{ .token.Claims.login }}"
    - name: "X-Last-Name"
      value: "{{ .token.Claims.lastName }}"
    - name: "X-First-Name"
      value: "{{ .token.Claims.firstName }}"
