apiVersion: getambassador.io/v2
kind: Filter
metadata:
  name: "facesystems-jwt-filter"
spec:
  JWT:
    jwksURI: "http://identity:8000/auth/.well-known/jwks.json"
    insecureTLS: true
    renegotiateTLS: freelyAsClient
    validAlgorithms:
    - "RS256"
    requireAudience: false
    requireIssuer: false
    requireIssuedAt: false
    requireExpiresAt: false
    requireNotBefore: false
    injectRequestHeaders:
    - name: "X-Token-String"
      value: "{{ .token.Raw }}"
    - name: "X-Admin"
      value: "{{ .token.Claims.isAdmin }}"
    - name: "X-Email"
      value: "{{ .token.Claims.email }}"
    - name: "X-UserId"
      value: "{{ .token.Claims.id }}"
    - name: "X-Last-Name"
      value: "{{ .token.Claims.lastName }}"
    - name: "X-First-Name"
      value: "{{ .token.Claims.firstName }}"
