apiVersion: skaffold/v2beta9
kind: Config
deploy:
  helm:
    releases:
      - name: aes
        chartPath: helm-chart
        namespace: otus
        skipBuildDependencies: false
        createNamespace: true
---
apiVersion: skaffold/v2beta9
kind: Config
deploy:
  kubectl:
    defaultNamespace: otus
    manifests:
      - ambassador/*
