{{- if .Values.ingress.enabled -}}
{{- $fullName := include "api-gateway-chart.fullname" . -}}
{{- $svcPort := .Values.servicePort -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "api-gateway-chart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/app-root: /otusapp/vaagn
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: /
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
        {{- end }}
  {{- end }}
{{- end }}
