apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configName }}
data:
  RABBITMQ_ORDERS_QUEUE: {{ .Values.rabbitmqOrdersQueue }}
  RABBITMQ_URI: {{ .Values.rabbitmqUri }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
data:
  DATABASE_URI: {{ printf "postgresql+psycopg2://%s:%s@%s:%s/%s" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword (include "postgresql.fullname" .) .Values.postgresql.service.port .Values.postgresql.postgresqlDatabase  | b64enc | quote }}
  MINIO_CONFIG: {{ .Values.minioClientConfig | b64enc | quote }}